pull_request_rules:
  - name: "Automatic merge when CI passes and approved"
    conditions:
      - or:
          - "#approved-reviews-by>=1"
          - "author=fabien-marty"
      - "check-success=build"
      - "base=main"
    actions:
      merge:
        method: squash
        commit_message_template: "{{ title }}"
